/* Copyright (c) 2026 zzz27578 and CentDeck contributors.
 * SPDX-License-Identifier: AGPL-3.0-only */
import { errorText } from '../core/i18n.js';
import { text as i18nText, template as i18nTpl } from '../core/i18n.js';
import { el, esc, toast, confirmDlg, openModal, promptDlg } from '../core/ui.js';
import { refreshAppearance, mountPluginFrame } from '../core/extensions.js';
import { userSkills } from '../core/skill-catalog.js';
import { icon } from '../core/icons.js';
const intro=(title,text)=>`<div class="extension-intro"><h2>${title}</h2><p>${text}</p></div>`;
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function pick(multiple=false,directory=false,accept=''){return new Promise(resolve=>{const input=document.createElement('input');input.type='file';input.multiple=multiple;input.accept=accept;if(directory)input.webkitdirectory=true;input.onchange=()=>resolve([...input.files]);input.oncancel=()=>resolve([]);input.click();});}
function protect(fn){return async (...args)=>{try{await fn(...args);}catch(e){toast(e.message,'error');}};}
export async function renderExtensions(app,content,tab){
  const request=app.api.extension;
  if(tab==='plugins'){
    const {plugins}=await request('extensions');if(!content.isConnected)return;
    content.innerHTML=intro(i18nText('扩展你的创作空间'),i18nText('插件为平台增加功能，Skills 教助手使用功能。导入的插件默认停用，你可以检查权限后启用。'))+i18nTpl`<div class="extension-toolbar"><input class="ipt" data-search placeholder="搜索插件" aria-label="搜索插件"><button class="btn primary" data-import>导入插件 JSON</button><button class="btn" data-url>从链接下载</button><button class="btn" data-folder>导入前端文件夹</button><button class="btn" data-html>导入 HTML 风格</button></div><div class="extension-grid"></div>`;
    const grid=content.querySelector('.extension-grid');
    const render=(query='')=>{grid.innerHTML='';for(const p of plugins.filter(p=>p.manifest.id!=='official-inspector').filter(p=>(p.manifest.name+p.manifest.description).toLowerCase().includes(query.toLowerCase()))){
      const m=p.manifest,card=el(i18nTpl`<article class="extension-card"><div class="extension-card-top"><span class="extension-badge">${p.official?i18nText('官方'):i18nText('本地导入')}</span><label class="extension-toggle"><input type="checkbox" ${p.enabled?'checked':''} role="switch" aria-label="启用 ${esc(p.official?i18nText(m.name):m.name)}"><i class="switch-track" aria-hidden="true"></i><span>${p.enabled?i18nText('已启用'):i18nText('已停用')}</span></label></div><h2>${esc(p.official?i18nText(m.name):m.name)}</h2><p>${esc(p.official?i18nText(m.description||''):m.description||'')}</p><div class="extension-meta">v${esc(m.version)} · ${esc(m.author||i18nText('未署名'))}</div><div class="extension-tags">${m.permissions.map(x=>`<span>${esc({themes:i18nText('主页风格'),panels:i18nText('隔离面板'),tools:i18nText('项目摘要'),skills:i18nText('Agent 技能')}[x]||x)}</span>`).join('')}</div><footer><button class="btn" data-settings>设置与详情</button><button class="btn ghost" data-download>导出插件</button>${!p.official?i18nText('<button class="btn ghost danger" data-remove>卸载</button>'):''}</footer></article>`);
      card.querySelector('input').onchange=protect(async e=>{await request('plugins/action',{id:m.id,action:e.target.checked?'enable':'disable'});await refreshAppearance();app.bus.emit('skills');await renderExtensions(app,content,tab);});
      card.querySelector('[data-download]').onclick=()=>download(m.id+'.centdeck-plugin.json',JSON.stringify({manifest:m,files:p.files},null,2));
      card.querySelector('[data-remove]')?.addEventListener('click',protect(async()=>{if(!await confirmDlg({title:i18nText('卸载插件'),body:i18nTpl`卸载 ${esc(p.official?i18nText(m.name):m.name)}？项目文件会保留。`,okLabel:i18nText('卸载')}))return;await request('plugins/action',{id:m.id,action:'remove'});await refreshAppearance();app.bus.emit('skills');await renderExtensions(app,content,tab);}));
      card.querySelector('[data-settings]').onclick=()=>{
        const body=el(i18nTpl`<div class="extension-details"><p>${esc(p.official?i18nText(m.description||''):m.description||'')}</p><p>编号：<code>${esc(m.id)}</code> · API v${m.apiVersion}</p><p>权限：${esc(m.permissions.join(' / '))}</p><p>风格 ${(m.themes||[]).length} · 面板 ${(m.panels||[]).length} · 技能 ${(m.skills||[]).length} · 工具 ${(m.tools||[]).length}</p>${m.id==='official-styles'?i18nText('<p>开启后，首页右上角显示「切换风格」。关闭后立即恢复默认黑白蓝。亮暗模式独立保存。</p>'):''}<div data-panels></div></div>`);
        for(const panel of m.panels||[]){const button=el(i18nTpl`<button class="btn">打开 ${esc(panel.name)}</button>`);button.disabled=!p.enabled;button.onclick=()=>{const host=el('<div class="plugin-panel-host"></div>');openModal({title:panel.name,body:host,width:900});mountPluginFrame(host,p,panel.file,app);};body.querySelector('[data-panels]').append(button);}
        const fields=Object.entries(m.settingsSchema||{});
        if(fields.length){const form=el(i18nTpl`<form class="extension-form">${fields.map(([key,f])=>`<label>${esc(f.label)}<input name="${esc(key)}" type="${f.type==='boolean'?'checkbox':f.type==='number'?'number':'text'}" ${f.type==='boolean'?(p.settings[key]?'checked':''):`value="${esc(p.settings[key])}"`}></label>`).join('')}<button class="btn primary">保存插件设置</button><p role="status"></p></form>`);body.append(form);form.onsubmit=protect(async e=>{e.preventDefault();const settings=Object.fromEntries(fields.map(([key,f])=>[key,f.type==='boolean'?form.elements[key].checked:f.type==='number'?Number(form.elements[key].value):form.elements[key].value]));await request('plugins/action',{id:m.id,action:'configure',settings});p.settings=settings;form.querySelector('[role=status]').textContent=i18nText('已保存，重新打开面板后生效');});}
        openModal({title:(p.official?i18nText(m.name):m.name)+i18nText(' · 插件设置'),body,width:620});
      };grid.append(card);
    }};render();content.querySelector('[data-search]').oninput=e=>render(e.target.value);
    async function install(bundle){await request('extensions',bundle);toast(i18nText('已导入，请检查后开启插件'),'ok');await renderExtensions(app,content,tab);}
    content.querySelector('[data-url]').onclick=protect(async()=>{const value=await promptDlg({title:i18nText('从链接下载插件'),label:i18nText('插件 JSON 的 HTTPS 地址'),placeholder:'https://raw.githubusercontent.com/.../plugin.json',okLabel:i18nText('下载并导入')});if(!value)return;const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password)throw Error(i18nText('请使用不含凭证的 HTTPS 地址'));const r=await fetch(url,{credentials:'omit',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(i18nText('下载失败：')+r.status);const text=await r.text();if(text.length>8*1024*1024)throw Error(i18nText('插件超过 8 MB'));await install(JSON.parse(text));});
    content.querySelector('[data-import]').onclick=protect(async()=>{const [f]=await pick(false,false,'.json');if(f)await install(JSON.parse(await f.text()));});
    const importFrontend=async directory=>{
      const selected=await pick(directory,directory,directory?'':'.html,.htm');if(!selected.length)return;
      const files={};for(const file of selected){if(!/\.(html|css|js|json|md|svg)$/i.test(file.name))continue;const name=directory?file.webkitRelativePath.split('/').slice(1).join('/'):file.name;files[name]=await file.text();}
      const manifestFile=Object.keys(files).find(n=>n==='manifest.json');
      if(manifestFile){await install({manifest:JSON.parse(files[manifestFile]),files});return;}
      const home=Object.keys(files).find(n=>n==='index.html')||Object.keys(files).find(n=>/\.html?$/.test(n));if(!home)throw Error(i18nText('请选择包含 HTML 的前端文件'));
      const id='custom-'+Date.now().toString(36);await install({manifest:{apiVersion:1,id,name:selected[0].webkitRelativePath?.split('/')[0]||selected[0].name,version:'1.0.0',description:i18nText('导入的自定义主页，在隔离预览中运行；项目导航保留在外层。'),permissions:['themes'],themes:[{id,name:i18nText('自定义 · ')+home,home,tokens:{}}]},files});
    };
    content.querySelector('[data-folder]').onclick=protect(()=>importFrontend(true));content.querySelector('[data-html]').onclick=protect(()=>importFrontend(false));
  }
  if(tab==='skills'){
    const skills=userSkills(await request('skills'));
    content.innerHTML=intro(i18nText('让助手更懂百映'),i18nText('管理你创建和导入的技能。基础技能由平台自动启用，助手按任务需要使用。'))+i18nText('<div class="extension-toolbar"><button class="btn primary" data-import>导入 SKILL.md</button><button class="btn" data-new>新建技能</button></div><div class="extension-grid"></div>');
    const edit=(skill)=>{
      const body=el(i18nTpl`<form class="extension-form"><label>技能编号<input name="id" required pattern="[a-z][a-z0-9-]{1,79}" value="${esc(skill?.id||'my-skill')}"></label><label>显示名称<input name="name" required value="${esc(skill?.name||i18nText('我的技能'))}"></label><label>说明<input name="desc" value="${esc(skill?.desc||'')}"></label><label>SKILL.md<textarea name="content" rows="12">${esc(skill?.content||i18nText('---\nname: my-skill\ndescription: When to use this skill\n---\n\n先读取当前项目，再根据要求进行修改。'))}</textarea></label><button class="btn primary">保存技能</button></form>`);
      const close=openModal({title:skill?i18nText('编辑技能'):i18nText('新建 Agent 技能'),body,width:700});body.onsubmit=protect(async e=>{e.preventDefault();await request('skills',Object.fromEntries(new FormData(body)),'PUT');close();app.bus.emit('skills');await renderExtensions(app,content,tab);});
    };
    content.querySelector('[data-new]').onclick=()=>edit(null);
    content.querySelector('[data-import]').onclick=protect(async()=>{const [file]=await pick(false,false,'.md');if(!file)return;const text=await file.text();const id=text.match(/^name:\s*(.+)$/m)?.[1]?.trim().replace(/['"]/g,'')||'skill-'+Date.now().toString(36);edit({id,name:id,content:text});});
    if(!skills.length)content.querySelector('.extension-grid').innerHTML=i18nText('<div class="empty">还没有自定义技能。可以新建或导入 SKILL.md。</div>');
    for(const s of skills){const card=el(i18nTpl`<article class="extension-card"><div class="extension-card-top"><span class="extension-badge">${s.source==='local'?i18nText('我的技能'):i18nText('扩展技能')}</span><label class="extension-toggle"><input type="checkbox" ${s.enabled?'checked':''} role="switch" aria-label="启用 ${esc(s.name)}"><i class="switch-track" aria-hidden="true"></i><span>启用</span></label></div><h2>${esc(s.name)}</h2><p>${esc(s.desc)}</p><footer><button class="btn" data-read>阅读规范</button>${s.source==='local'?i18nText('<button class="btn ghost" data-edit>编辑</button><button class="btn ghost danger" data-remove>删除</button>'):''}</footer></article>`);
      card.querySelector('input').onchange=protect(async e=>{await request('skills',{id:s.id,enabled:e.target.checked},'PUT');app.bus.emit('skills');toast(i18nText('后续任务将使用新的技能配置'),'ok');});
      card.querySelector('[data-read]').onclick=()=>openModal({title:s.name,body:el(`<pre class="extension-source">${esc(s.content)}</pre>`),width:800});
      card.querySelector('[data-edit]')?.addEventListener('click',()=>edit(s));
      card.querySelector('[data-remove]')?.addEventListener('click',protect(async()=>{await request('skills',{id:s.id,action:'remove'},'PUT');await renderExtensions(app,content,tab);}));content.querySelector('.extension-grid').append(card);
    }
  }
  if(tab==='tools'){
    const list=await request('tools');content.innerHTML=intro(i18nText('同一套工具，两种调用方式'),i18nText('内置 Agent 与 MCP 使用相同注册表。创建工具受模式、范围、版本与锁定检查约束；插件工具随插件启停。'))+i18nTpl`<div class="extension-tool-list"><details class="tool-group"><summary><span>官方工具</span><span class="extension-badge">${list.filter(t=>!t.name.startsWith('plugin_')||t.name.startsWith('plugin_official_')).length} 项</span></summary>${list.filter(t=>!t.name.startsWith('plugin_')||t.name.startsWith('plugin_official_')).map(t=>`<details><summary><code>${esc(t.name)}</code><span class="extension-badge">${t.annotations.readOnlyHint?i18nText('读取'):i18nText('操作')}</span></summary><p>${esc(errorText(t.description))}</p><pre class="extension-source">${esc(JSON.stringify(t.inputSchema,null,2))}</pre></details>`).join('')}</details><details class="tool-group"><summary>扩展工具<span class="extension-badge">${list.filter(t=>t.name.startsWith('plugin_')&&!t.name.startsWith('plugin_official_')).length} 项</span></summary>${list.filter(t=>t.name.startsWith('plugin_')&&!t.name.startsWith('plugin_official_')).map(t=>`<details><summary>${esc(t.name)}</summary><p>${esc(errorText(t.description))}</p><pre>${esc(JSON.stringify(t.inputSchema,null,2))}</pre></details>`).join('')}</details></div>`;
  }
  if(tab==='mcp'){
    const config=await request('mcp/config');
    const json=JSON.stringify({mcpServers:{centdeck:{command:config.command,args:config.args,env:config.env}}},null,2);
    content.innerHTML=intro(i18nText('连接你常用的 AI 助手'),i18nText('将支持 MCP 的 AI 应用接入百映，在对话中查看项目、调整页面并完成设计。'))+i18nTpl`<div class="settings-block extension-form"><label class="extension-toggle"><input type="checkbox" role="switch" aria-label="开启本机 MCP" data-enabled ${config.enabled?'checked':''}><i class="switch-track" aria-hidden="true"></i><span>开启 MCP 连接</span></label><label>允许助手执行的操作<select data-mode><option value="plan" ${config.mode==='plan'?'selected':''}>查看项目与提供建议</option><option value="create" ${config.mode==='create'?'selected':''}>编辑项目与操作页面</option></select></label><p>连接地址：<code>${esc(config.endpoint)}</code></p><p>配置根据百映当前的安装位置自动生成，连接凭证会自动读取，无需手动填写。</p><div class="mcp-connect-actions"><button class="btn primary" data-copy>${icon('copy',16)}复制连接配置</button><button class="btn ghost" data-rotate>更新连接凭证</button></div><details class="mcp-config-details"><summary>查看连接配置</summary><pre class="extension-source" data-config>${esc(json)}</pre></details><p role="status" data-result></p></div><div class="settings-block mcp-user-guide"><h2>开始使用</h2><ol><li><b>添加百映连接</b><p>复制上方配置，在你使用的 AI 应用中打开 MCP 或工具连接设置，添加并启用百映。</p></li><li><b>打开要编辑的项目</b><p>保持百映运行，在工作台打开项目，然后告诉 AI 助手你希望查看或修改的内容。</p></li><li><b>查看设计结果</b><p>回到百映预览修改后的页面，继续调整细节，或通过版本历史找回之前的页面版本。</p></li></ol><h3>在百映对话中使用外部助手</h3><p>连接完成后，在对话的模型菜单中选择“外部 MCP 助手”。再请已连接的 AI 应用接手这段百映对话。处理过程中，请保持百映与 AI 应用运行。</p><h3>更换电脑或安装位置</h3><p>请在同一台电脑上运行百映与 AI 应用。移动百映的安装目录后，重新启动百映，再复制新的连接配置。</p></div>`;
    const save=protect(async()=>{await request('mcp/config',{enabled:content.querySelector('[data-enabled]').checked,mode:content.querySelector('[data-mode]').value},'PUT');toast(i18nText('MCP 配置已保存'),'ok');});content.querySelector('[data-enabled]').onchange=save;content.querySelector('[data-mode]').onchange=save;
    content.querySelector('[data-copy]').onclick=protect(async()=>{await navigator.clipboard.writeText(json);content.querySelector('[data-result]').textContent=i18nText('配置已复制');});
    content.querySelector('[data-rotate]').onclick=protect(async()=>{await request('mcp/config',{rotate:true},'PUT');content.querySelector('[data-result]').textContent=i18nText('连接凭证已更新，后续连接将自动使用新凭证。');});
  }
}
