import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createRequire} from 'node:module';
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'centdeck-mcp-improved-'));
process.env.CENTDECK_CONFIG_DIR=path.join(tmp,'config');process.env.CENTDECK_PROJECTS_DIR=path.join(tmp,'projects');
const require=createRequire(import.meta.url),store=require('../server/store'),ext=require('../server/extensions'),mcp=require('../server/mcp'),changes=require('../server/changes'),{createBridge}=require('../server/ui-bridge');
try{
  ext.mcpConfig({enabled:true,mode:'create'});
  const session=(await mcp.dispatch({method:'initialize',params:{protocolVersion:'2025-03-26'}})).sid;
  const call=async(name,args={})=>(await mcp.dispatch({method:'tools/call',params:{name,arguments:args}},session)).result;
  const decode=r=>{assert(!r.isError,r.content[0].text);return JSON.parse(r.content[0].text);};
  const catalog=(await mcp.dispatch({method:'tools/list'},session)).result.tools;
  for(const name of ['read_page','write_files','patch_text','rename_page','project_context','capture_page'])assert(catalog.find(t=>t.name===name).inputSchema.required.includes('projectId'));
  assert(!catalog.find(t=>t.name==='read_skill').inputSchema.required.includes('projectId'));
  assert.match((await call('read_page',{path:'index.html'})).content[0].text,/projectId/);
  const p=store.createProject({blank:true,name:'MCP improvements'}),id=p.id;
  let read=decode(await call('read_page',{projectId:id,path:'index.html'}));
  decode(await call('write_files',{projectId:id,files:[{path:'index.html',content:'<title>HTML title</title><h1>Content</h1>',baseHash:read.baseHash,title:'Original'}]}));
  read=decode(await call('read_page',{projectId:id,path:'index.html'}));assert.equal(read.title,'Original');
  const design=decode(await call('read_page',{projectId:id,path:'DESIGN.md'}));
  const commit=decode(await call('write_files',{projectId:id,files:[{path:'DESIGN.md',content:'# Updated design\nCobalt and paper.',baseHash:design.baseHash},{path:'index.html',content:read.content,baseHash:read.baseHash,title:'New title'}]}));
  assert.equal(store.getProject(id).pages[0].title,'New title');assert.match(changes.read(id,'DESIGN.md'),/Updated design/);
  assert((await call('rename_page',{projectId:id,path:'index.html',title:'Stale',baseHash:read.baseHash})).isError,'content hash alone must not overwrite a newer title');
  changes.undo(id,commit.id);assert.equal(store.getProject(id).pages[0].title,'Original');assert.equal(changes.read(id,'DESIGN.md'),design.content);
  read=decode(await call('read_page',{projectId:id,path:'index.html'}));
  const renamed=decode(await call('rename_page',{projectId:id,path:'index.html',title:'Renamed',baseHash:read.baseHash}));assert.equal(changes.read(id,'index.html'),read.content);assert.equal(store.getProject(id).pages[0].title,'Renamed');
  let project=store.getProject(id);project.pages[0].title='User rename';store.saveProject(id,project);assert.throws(()=>changes.undo(id,renamed.id),/标题已变化/);
  const before=changes.read(id,'index.html');read=decode(await call('read_page',{projectId:id,path:'index.html'}));
  const bad=await call('write_files',{projectId:id,files:[{path:'index.html',baseHash:read.baseHash,content:'<h1>Partial</h1>'},{path:'../escape.md',baseHash:changes.hash(null),content:'No'}]});assert(bad.isError);assert.equal(changes.read(id,'index.html'),before);
  ext.mcpConfig({mode:'plan'});assert((await call('rename_page',{projectId:id,path:'index.html',title:'No',baseHash:read.baseHash})).isError);ext.mcpConfig({mode:'create'});
  let clock=1000,callbacks=[];
  const bridge=createBridge({now:()=>clock,setTimer:fn=>{callbacks.push(fn);return fn;},clearTimer:fn=>callbacks=callbacks.filter(x=>x!==fn),retention:90000,timeout:15000});
  const beat=(clientId,doc='doc1',projectId=id,focused=false)=>bridge.heartbeat({clientId,documentId:doc,state:{projectId,focused,controls:[]}});
  beat('tab');clock+=20000;assert.equal(bridge.snapshot()[0].connection,'background-delayed','background tab must not disappear at 15 seconds');
  const action=bridge.send({clientId:'tab',projectId:id,action:'refresh'}),cmd=beat('tab').commands[0];assert(cmd.expiresAt>clock);
  bridge.complete({clientId:'tab',documentId:'doc1',id:cmd.id,result:{view:'edit',controls:[]}});assert.equal((await action).view,'edit');
  beat('tab');const interrupted=bridge.send({clientId:'tab',projectId:id,action:'click',target:'old'});const rejected=assert.rejects(interrupted,/DOCUMENT_REPLACED/);beat('tab','doc2');await rejected;assert.deepEqual(beat('tab','doc2').commands,[]);
  assert.throws(()=>bridge.send({clientId:'tab',projectId:'wrong',action:'click'}),/CLIENT_UNAVAILABLE/);
  beat('second','s',id);assert.throws(()=>bridge.send({projectId:id,action:'refresh'}),/AMBIGUOUS_CLIENT/);
  const expired=bridge.send({clientId:'tab',projectId:id,action:'refresh'});const timeout=assert.rejects(expired,/UI_TIMEOUT/);callbacks[0]();await timeout;assert.equal(beat('tab','doc2').commands.length,0);
  console.log('MCP improvements: required project IDs, Markdown transaction/rollback, title CAS/undo, reload invalidation, delayed heartbeat and client isolation passed');
}finally{if(path.dirname(tmp)===os.tmpdir()&&path.basename(tmp).startsWith('centdeck-mcp-improved-'))fs.rmSync(tmp,{recursive:true,force:true});}
